BEGIN 
	
	INSERT INTO APP_HIST_CLINICA.PLAN_TYPES(PLAN_TYPE_ID, DESCRIPTION, IS_ACTIVE) VALUES (1, 'Platino',	1);
	INSERT INTO APP_HIST_CLINICA.PLAN_TYPES(PLAN_TYPE_ID, DESCRIPTION, IS_ACTIVE) VALUES (2, 'Oro', 1);
	INSERT INTO APP_HIST_CLINICA.PLAN_TYPES(PLAN_TYPE_ID, DESCRIPTION, IS_ACTIVE) VALUES (3, 'Plata', 1);
	INSERT INTO APP_HIST_CLINICA.PLAN_TYPES(PLAN_TYPE_ID, DESCRIPTION, IS_ACTIVE) VALUES (4, 'Básico', 1); 

--

COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      raise_application_error(-20000, SQLCODE || '=>' || SQLERRM, TRUE);   
END;
/
