BEGIN
	
	INSERT INTO APP_HIST_CLINICA.PATIENTS (PATIENT_ID, DOCUMENT_NUMBER, DOCUMENT_TYPE, NAME_1, NAME_2, LASTNAME_1, LASTNAME_2, BIRTH_DATE, GENDER, SEX, ADDRESS, PHONE_NUMBER, AFFILIATION_DATE, PLAN_TYPE_ID, ACTIVE_DATE, IS_ACTIVE) 
	VALUES (1, 1642367384,'Cédula de Ciudadanía', 'Carissa','Kylee', 'Johnson', 'Guthrie', TO_DATE('1975-08-26', 'yyyy-mm-dd'),'Femenino','M', '9576 Imperdiet St.','3175114176',TO_DATE('2018-05-16', 'yyyy-mm-dd'),1,TO_DATE('2015-07-29', 'yyyy-mm-dd'),1);

	INSERT INTO APP_HIST_CLINICA.PATIENTS (PATIENT_ID, DOCUMENT_NUMBER, DOCUMENT_TYPE, NAME_1, NAME_2, LASTNAME_1, LASTNAME_2, BIRTH_DATE, GENDER, SEX, ADDRESS, PHONE_NUMBER, AFFILIATION_DATE, PLAN_TYPE_ID, ACTIVE_DATE, IS_ACTIVE)
	VALUES (2, 123456789, 'Cédula de Ciudadanía', 'John', '', 'Doe', '', TO_DATE('1984-04-30', 'yyyy-mm-dd'), 'Masculino', 'H', 'Sesame Street 123', '3124567890', systimestamp, 4, systimestamp, 1);

--

COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      raise_application_error(-20000, SQLCODE || '=>' || SQLERRM, TRUE);   
END;
/
