BEGIN 
	
	INSERT INTO APP_HIST_CLINICA.SPECIALTIES(SPECIALTY_ID, NAME) VALUES (1, 'medicina general');
	INSERT INTO APP_HIST_CLINICA.SPECIALTIES(SPECIALTY_ID, NAME) VALUES (2, 'hematología');
	INSERT INTO APP_HIST_CLINICA.SPECIALTIES(SPECIALTY_ID, NAME) VALUES (3, 'cardiología');
	INSERT INTO APP_HIST_CLINICA.SPECIALTIES(SPECIALTY_ID, NAME) VALUES (4, 'medicina interna'); 

--

COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      raise_application_error(-20000, SQLCODE || '=>' || SQLERRM, TRUE);   
END;
/
