BEGIN 

	INSERT INTO APP_HIST_CLINICA.WORK_PLACES(HEALTHCARE_PROFESSIONAL_ID, CARE_CENTER_ID)
	VALUES (1, 1);
	
	INSERT INTO APP_HIST_CLINICA.WORK_PLACES(HEALTHCARE_PROFESSIONAL_ID, CARE_CENTER_ID)
	VALUES (2, 2);
	
--

COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      raise_application_error(-20000, SQLCODE || '=>' || SQLERRM, TRUE);   
END;
/
