-- Run as SYS (connect as SYS AS SYSDBA before running)
ALTER SESSION SET CONTAINER = XEPDB1;

-- Create application user with explicit tablespace assignment
CREATE USER APP_HIST_CLINICA IDENTIFIED BY password
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

-- Grant necessary privileges (modern Oracle practice)
GRANT CREATE SESSION TO APP_HIST_CLINICA;
GRANT CONNECT, RESOURCE TO APP_HIST_CLINICA;
--GRANT CREATE TABLE TO APP_HIST_CLINICA;
--GRANT CREATE VIEW TO APP_HIST_CLINICA;
--GRANT CREATE PROCEDURE TO APP_HIST_CLINICA;
--GRANT CREATE SEQUENCE TO APP_HIST_CLINICA;  -- Instead of RESOURCE
--GRANT CREATE JOB TO APP_HIST_CLINICA;
GRANT CREATE JOB TO APP_HIST_CLINICA;
GRANT EXECUTE ON DBMS_SCHEDULER TO APP_HIST_CLINICA;
