DROP SEQUENCE APP_HIST_CLINICA.SEQ_CARE_CENTERS;

DROP SEQUENCE APP_HIST_CLINICA.SEQ_HEALTHCARE_PROFESSIONALS;

DROP SEQUENCE APP_HIST_CLINICA.SEQ_MEDICAL_RECORDS;

DROP SEQUENCE APP_HIST_CLINICA.SEQ_PATIENTS;

DROP SEQUENCE APP_HIST_CLINICA.SEQ_PLAN_TYPES;

DROP SEQUENCE APP_HIST_CLINICA.SEQ_SPECIALTIES;