DROP TABLE APP_HIST_CLINICA.CARE_CENTERS PURGE;

DROP TABLE APP_HIST_CLINICA.HEALTHCARE_PROFESSIONALS PURGE;

DROP TABLE APP_HIST_CLINICA.MEDICAL_RECORDS PURGE;

DROP TABLE APP_HIST_CLINICA.PATIENTS PURGE;

DROP TABLE APP_HIST_CLINICA.PLAN_TYPES PURGE;

DROP TABLE APP_HIST_CLINICA.SPECIALTIES PURGE;

DROP TABLE APP_HIST_CLINICA.WORK_PLACES PURGE;