DROP PACKAGE APP_HIST_CLINICA.PKG_PATIENTS;

DROP PACKAGE APP_HIST_CLINICA.PGK_MEDICAL_RECORDS;

DROP PACKAGE APP_HIST_CLINICA.PKG_APP_CREATE_PATIENTS;

DROP PACKAGE APP_HIST_CLINICA.PKG_APP_CREATE_MEDICAL_RECORDS;